name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe:
    name: Build EXE
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clean previous builds
      run: |
        rm -rf build/ dist/ __pycache__/
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --console ok_school_life.py
        echo "=== 生成文件验证 ==="
        dir dist\
        echo "===================="

    - name: Rename EXE file
      run: |
        $version = $env:GITHUB_REF_NAME.Substring(1)  # Remove 'v' prefix from tag
        $newName = "ok_school_life-windows-x64-$version.exe"
        Rename-Item -Path "dist\ok_school_life.exe" -NewName $newName
        echo "Renamed to $newName"
        dir dist\
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/ok_school_life-windows-x64-*.exe

  create-release:
    name: Create Release
    needs: build-exe
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-exe
        path: release-files
        
    - name: Verify EXE file
      run: |
        echo "=== 文件列表 ==="
        ls -R release-files
        if ls release-files/ok_school_life-windows-x64-*.exe 1> /dev/null 2>&1; then
          echo "✅ EXE 文件存在"
        else
          echo "❌ 错误：EXE 文件未找到！"
          exit 1
        fi
        
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "Automated EXE release"
        artifacts: "release-files/ok_school_life-windows-x64-*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}