name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe:
    # ... 保持原有 build-exe job 不变 ...

  create-release:
    name: Create Release
    needs: build-exe
    runs-on: ubuntu-latest
    steps:
      # ... 保持原有 checkout 和 artifact 步骤不变 ...

      - name: Extract contributors
        id: contributors
        run: |
          current_tag="${{ github.ref_name }}"
          previous_tag=$(git describe --tags --abbrev=0 "$current_tag^" 2>/dev/null || echo "")
          
          if [ -z "$previous_tag" ]; then
            contributors=$(git log --pretty="%an")
          else
            contributors=$(git log --pretty="%an" "$previous_tag".."$current_tag")
          fi

          unique_contributors=$(echo "$contributors" | sort | uniq)
          contributors_list=$(echo "$unique_contributors" | awk '{ printf "- @%s\n", $0 }' | sed 's/ /\\ /g')

          delimiter=$(openssl rand -hex 16)
          echo "contributors<<${delimiter}" >> $GITHUB_OUTPUT
          echo "$contributors_list" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # ... 保持原有 changelog 和 timestamp 步骤不变 ...

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "🎉 Release ${{ github.ref_name }}"
          body: |
            ## 🚀 版本更新说明
            
            ### 👥 贡献者致谢
            ${{ steps.contributors.outputs.contributors || '暂无贡献者信息' }}

            ### 📦 更新内容
            ${{ steps.changelog.outputs.changelog }}
            
            ### 🔧 构建信息
            - ${{ steps.timestamp.outputs.time }}
            - 📦 包含架构: x86 & x64
            - 🏷️ 版本标签: ${{ github.ref_name }}
            - 🔗 触发提交: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            ### 📥 下载统计
            文件下载统计（每小时自动更新）：
            ```bash
            # 使用 GitHub API 获取下载量
            curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq '.assets[] | "\(.name): \(.download_count)"'
            ```

            ### 📦 依赖关系
            查看依赖项目: [![Dependents](https://img.shields.io/badge/依赖项目-点击查看-blue)](https://github.com/${{ github.repository }}/network/dependents)
          files: |
            release-files/ok_school_life-windows-x64-*.exe
            release-files/ok_school_life-windows-x86-*.exe