name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe:
    name: Build EXE (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
        include:
          - arch: x64
            python_arch: x64
          - arch: x86
            python_arch: x86

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Clean previous builds
      run: |
        Remove-Item -Recurse -Force build, dist, __pycache__ -ErrorAction SilentlyContinue
        if (Test-Path dist) { Remove-Item -Recurse -Force dist }
        if (Test-Path build) { Remove-Item -Recurse -Force build }
        if (Test-Path __pycache__) { Remove-Item -Recurse -Force __pycache__ }

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: ${{ matrix.python_arch }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --console ok_school_life.py
        echo "=== 生成文件验证 ==="
        dir dist
        echo "===================="

    - name: Rename EXE file
      run: |
        $version = $env:GITHUB_REF_NAME.Substring(1)
        $newName = "ok_school_life-windows-${{ matrix.arch }}-$version.exe"
        Rename-Item -Path "dist\ok_school_life.exe" -NewName $newName
        echo "重命名为 $newName"
        dir dist
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe-${{ matrix.arch }}
        path: dist/ok_school_life-windows-${{ matrix.arch }}-*.exe

  create-release:
    name: Create Release
    needs: build-exe
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-files
        merge-multiple: true  # 关键修改：合并所有文件到同一目录

    - name: Verify EXE files
      run: |
        echo "=== 文件列表 ==="
        ls -R release-files
        
        # 修正后的路径检查
        if ls release-files/ok_school_life-windows-x64-*.exe 1> /dev/null 2>&1; then
          echo "✅ x64 EXE 文件存在"
        else
          echo "❌ 错误：x64 EXE 文件未找到！"
          exit 1
        fi
        
        if ls release-files/ok_school_life-windows-x86-*.exe 1> /dev/null 2>&1; then
          echo "✅ x86 EXE 文件存在"
        else
          echo "❌ 错误：x86 EXE 文件未找到！"
          exit 1
        fi

    - name: Get commit messages
      id: get-commits
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git fetch --tags --force
        
        previous_tag=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
        
        if [ -z "$previous_tag" ]; then
          messages=$(git log --pretty=format:"- %s (提交人: %an, 提交ID: %h)" --reverse)
          echo "这是第一个发布版本"
        else
          messages=$(git log --pretty=format:"- %s (提交人: %an, 提交ID: %h)" --reverse $previous_tag..${{ github.ref_name }})
          echo "变更范围: $previous_tag..${{ github.ref_name }}"
        fi
        
        delimiter=$(date +%s | sha256sum | base64 | head -c 10)
        echo "messages<<${delimiter}" >> $GITHUB_OUTPUT
        echo "$messages" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        BUILD_TIME: $(date -u '+%Y-%m-%d %H:%M:%S')
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ### 🚀 新版本发布
          
          #### 更新内容
          ${{ steps.get-commits.outputs.messages }}
          
          #### 构建信息
          - 版本号: ${{ github.ref_name }}
          - 构建时间: ${{ env.BUILD_TIME }}
          - 包含架构: x86 和 x64
        files: |
          release-files/ok_school_life-windows-x64-*.exe
          release-files/ok_school_life-windows-x86-*.exe