name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe:
    name: Build EXE (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
        include:
          - arch: x64
            python_arch: x64
          - arch: x86
            python_arch: x86

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Clean previous builds
      run: |
        rm -rf build/ dist/ __pycache__/
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: ${{ matrix.python_arch }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --console ok_school_life.py
        dir dist

    - name: Rename EXE file
      run: |
        $version = $env:GITHUB_REF_NAME.Substring(1)
        $newName = "ok_school_life-windows-${{ matrix.arch }}-$version.exe"
        Rename-Item -Path "dist\ok_school_life.exe" -NewName $newName
        dir dist
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe-${{ matrix.arch }}
        path: dist/ok_school_life-windows-${{ matrix.arch }}-*.exe

  create-release:
    name: Create Release
    needs: build-exe
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download x64 artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-exe-x64
        path: release-files

    - name: Download x86 artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-exe-x86
        path: release-files

    - name: Get commit messages
      id: get-commits
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git fetch --tags --force
        
        previous_tag=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
        
        if [ -z "$previous_tag" ]; then
          messages=$(git log --pretty=format:"- %s (by %an, %h)" --reverse)
          echo "这是第一个发布版本"
        else
          messages=$(git log --pretty=format:"- %s (by %an, %h)" --reverse $previous_tag..${{ github.ref_name }})
          echo "变更范围: $previous_tag..${{ github.ref_name }}"
        fi
        
        delimiter=$(date +%s | sha256sum | base64 | head -c 10)
        echo "messages<<${delimiter}" >> $GITHUB_OUTPUT
        echo "$messages" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ### 🚀 新版本发布
          
          #### 更新内容
          ${{ steps.get-commits.outputs.messages }}
          
          #### 构建信息
          - 版本号: ${{ github.ref_name }}
          - 构建时间: $(date -u '+%Y-%m-%d %H:%M:%S')
        files: |
          release-files/ok_school_life-windows-x64-*.exe
          release-files/ok_school_life-windows-x86-*.exe