name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe:
    name: Build EXE (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
        include:
          - arch: x64
            python_arch: x64
          - arch: x86
            python_arch: x86
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Clean workspace
        run: |
          Remove-Item -Recurse -Force build, dist, __pycache__ -ErrorAction SilentlyContinue

      - name: Setup Python ${{ matrix.python_arch }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: ${{ matrix.python_arch }}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        
      - name: Build executable
        run: |
          pyinstaller --onefile --console ok_school_life.py
          dir dist

      - name: Rename artifacts
        run: |
          $version = $env:GITHUB_REF_NAME.Substring(1)
          $newName = "ok_school_life-windows-${{ matrix.arch }}-$version.exe"
          Rename-Item -Path "dist\ok_school_life.exe" -NewName $newName
          dir dist
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-${{ matrix.arch }}
          path: dist/ok_school_life-windows-${{ matrix.arch }}-*.exe

  create-release:
    name: Create Release
    needs: build-exe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files
          merge-multiple: true

      - name: Verify files
        run: |
          echo "=== 文件验证 ==="
          ls -R release-files
          if ! ls release-files/ok_school_life-windows-x64-*.exe >/dev/null 2>&1; then
            echo "❌ x64 可执行文件缺失!"
            exit 1
          fi
          if ! ls release-files/ok_school_life-windows-x86-*.exe >/dev/null 2>&1; then
            echo "❌ x86 可执行文件缺失!"
            exit 1
          fi
          echo "✅ 所有文件验证通过"

      - name: Generate changelog
        id: changelog
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Release Bot"
          git fetch --tags --force
          
          current_tag="${{ github.ref_name }}"
          previous_tag=$(git describe --tags --abbrev=0 "$current_tag^" 2>/dev/null || echo "")

          if [ -z "$previous_tag" ]; then
            echo "范围: 初始提交到 $current_tag"
            messages=$(git log --reverse --pretty=format:"- %s%n  ↳ 描述: %b%n  ↳ 提交人: %an (%h)")
          else
            echo "范围: $previous_tag..$current_tag"
            messages=$(git log --reverse --pretty=format:"- %s%n  ↳ 描述: %b%n  ↳ 提交人: %an (%h)" "$previous_tag".."$current_tag")
          fi

          delimiter=$(openssl rand -hex 16)
          echo "changelog<<${delimiter}" >> $GITHUB_OUTPUT
          echo "$messages" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Generate timestamp
        id: timestamp
        run: |
          build_time=$(TZ="Asia/Shanghai" date +"%Y-%m-%d %H:%M:%S")
          echo "time=🕒 构建时间: $build_time (北京时间 UTC+8)" >> $GITHUB_OUTPUT

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "🎉 Release ${{ github.ref_name }}"
          body: |
            ## 🚀 版本更新说明
            
            ### 📦 更新内容
            ${{ steps.changelog.outputs.changelog }}
            
            ### 🔧 构建信息
            - ${{ steps.timestamp.outputs.time }}
            - 📦 包含架构: x86 & x64
            - 🏷️ 版本标签: ${{ github.ref_name }}
            - 🔗 触发提交: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          files: |
            release-files/ok_school_life-windows-x64-*.exe
            release-files/ok_school_life-windows-x86-*.exe