name: Build and Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'  # 强制语义化版本标签

permissions:
  contents: write
  security-events: write

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller safety

      - name: Security scan
        run: |
          safety check --full-report --output=security_report.md
          echo "SECURITY_REPORT<<EOF" >> $GITHUB_ENV
          cat security_report.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build executable
        run: |
          pyinstaller --onefile --console ok_school_life.py
          mv dist/ok_school_life.exe dist/ok_school_life-${{ matrix.arch }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.arch }}
          path: dist/ok_school_life-${{ matrix.arch }}.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Generate release notes
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: |
            categories:
              - title: "🚀 新增功能"
                labels: ["feature", "enhancement"]
              - title: "🐛 问题修复"
                labels: ["bug", "security"]
              - title: "♻️ 功能变更"
                labels: ["refactor", "change"]
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get contributors
        id: contributors
        run: |
          contributors=$(git log --pretty="%an" ${{ github.ref_name }}^..HEAD | sort -u | awk '{print "@"$0}' ORS=', ')
          echo "contributors=${contributors%, }" >> $GITHUB_OUTPUT

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "🎯 v${{ github.ref_name }} 版本发布"
          body: |
            ## 📅 发布日期: $(date -u +"%Y-%m-%d") (北京时间)

            ### 🔖 版本信息
            - **版本号**: ${{ github.ref_name }}
            - **构建分支**: ${{ github.ref }}
            - **提交哈希**: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            ### 📜 更新说明
            ${{ steps.changelog.outputs.changelog }}

            ### ⚠️ 已知问题
            - [ ] 待解决问题1
            - [ ] 待解决问题2

            ### 🔧 升级指南
            1. 备份现有配置
            2. 下载对应架构的可执行文件
            3. 替换旧版本文件

            ### 👥 贡献者
            ${{ steps.contributors.outputs.contributors }}

            ### 🔒 安全报告
            ```markdown
            ${{ env.SECURITY_REPORT }}
            ```
          files: |
            release-assets/ok_school_life-x64.exe
            release-assets/ok_school_life-x86.exe
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}

  post-release:
    name: Post Release
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Get download stats
        run: |
          echo "Download stats will be available at:"
          echo "https://api.github.com/repos/${{ github.repository }}/releases/${{ needs.release.outputs.release_id }}/assets"

      - name: Update dependency graph
        uses: actions/dependency-review-action@v3

      - name: Notify team
        run: |
          echo "Release published: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"