name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-exe:
    # ... (保持build-exe作业不变，同之前配置) ...

  create-release:
    name: Create Release
    needs: build-exe
    runs-on: ubuntu-latest
    
    steps:
    # ... (保持之前的checkout和下载步骤不变) ...

    - name: Get commit details
      id: get-commits
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git fetch --tags --force
        
        # 获取前一个标签
        previous_tag=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
        
        # 获取带描述信息的提交历史
        if [ -z "$previous_tag" ]; then
          echo "range=all" >> $GITHUB_OUTPUT
          messages=$(git log --pretty=format:"- %s%n  ↳ 描述: %b%n  ↳ 提交人: %an (%h)" --reverse)
        else
          echo "range=$previous_tag..${{ github.ref_name }}" >> $GITHUB_OUTPUT
          messages=$(git log --pretty=format:"- %s%n  ↳ 描述: %b%n  ↳ 提交人: %an (%h)" --reverse $previous_tag..${{ github.ref_name }})
        fi
        
        # 处理多行输出
        delimiter=$(date +%s | sha256sum | base64 | head -c 10)
        echo "messages<<${delimiter}" >> $GITHUB_OUTPUT
        echo "$messages" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Get Beijing time
      id: get-time
      run: |
        TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M:%S (北京时间)' >> time.txt
        echo "time=$(cat time.txt)" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ### 🚀 新版本发布 (北京时间)
          
          #### 📝 更新内容
          ${{ steps.get-commits.outputs.messages }}
          
          #### 🛠️ 构建信息
          - 版本号: ${{ github.ref_name }}
          - 构建时间: ${{ steps.get-time.outputs.time }}
          - 包含架构: x86 和 x64
          - 时区说明: 所有时间均为北京时间 (UTC+8)
        files: |
          release-files/ok_school_life-windows-x64-*.exe
          release-files/ok_school_life-windows-x86-*.exe